
name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Specify the operating system for the job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Action for deploying to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
          publish_dir: ./ # Directory to publish (your project's root for this ToDo app)
          # If your static files are in a 'dist' or 'build' folder, change 'publish_dir' accordingly.
